spring.application.name=backend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:taskmanagement}
spring.datasource.username=${POSTGRES_USER:taskmanagement}
spring.datasource.password=${POSTGRES_PASSWORD:taskmanagement}

spring.jpa.hibernate.ddl-auto=validate
